/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BookshelfPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian8 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  booksFolder: "Books",
  coversFolder: "Books/covers",
  googleBooksApiKey: "",
  duplicateIsbnAction: "open"
};

// src/settings.ts
var import_obsidian = require("obsidian");
var BookshelfSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Bookshelf \u8A2D\u5B9A" });
    new import_obsidian.Setting(containerEl).setName("\u66F8\u7C4D\u30CE\u30FC\u30C8\u306E\u4FDD\u5B58\u30D5\u30A9\u30EB\u30C0").setDesc("\u66F8\u7C4D\u30CE\u30FC\u30C8\u3092\u4FDD\u5B58\u3059\u308B\u30D5\u30A9\u30EB\u30C0\u306E\u30D1\u30B9\uFF08Vault \u30EB\u30FC\u30C8\u304B\u3089\u306E\u76F8\u5BFE\u30D1\u30B9\uFF09").addText(
      (text) => text.setPlaceholder("Books").setValue(this.plugin.settings.booksFolder).onChange(async (value) => {
        this.plugin.settings.booksFolder = value.trim() || "Books";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u8868\u7D19\u753B\u50CF\u306E\u30AD\u30E3\u30C3\u30B7\u30E5\u30D5\u30A9\u30EB\u30C0").setDesc("\u8868\u7D19\u753B\u50CF\uFF08WebP\uFF09\u3092\u4FDD\u5B58\u3059\u308B\u30D5\u30A9\u30EB\u30C0\u306E\u30D1\u30B9").addText(
      (text) => text.setPlaceholder("Books/covers").setValue(this.plugin.settings.coversFolder).onChange(async (value) => {
        this.plugin.settings.coversFolder = value.trim() || "Books/covers";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Google Books API \u30AD\u30FC\uFF08\u4EFB\u610F\uFF09").setDesc("\u30EC\u30FC\u30C8\u5236\u9650\u3092\u7DE9\u548C\u3059\u308B\u305F\u3081\u306B\u4EFB\u610F\u3067\u8A2D\u5B9A\u3067\u304D\u307E\u3059").addText(
      (text) => text.setPlaceholder("AIza...").setValue(this.plugin.settings.googleBooksApiKey).onChange(async (value) => {
        this.plugin.settings.googleBooksApiKey = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u91CD\u8907 ISBN \u6642\u306E\u52D5\u4F5C").setDesc("\u540C\u3058 ISBN \u306E\u30CE\u30FC\u30C8\u304C\u65E2\u306B\u5B58\u5728\u3059\u308B\u5834\u5408\u306E\u52D5\u4F5C\u3092\u9078\u629E\u3057\u3066\u304F\u3060\u3055\u3044").addDropdown(
      (dropdown) => dropdown.addOption("open", "\u65E2\u5B58\u30CE\u30FC\u30C8\u3092\u958B\u304F").addOption("overwrite", "\u65E2\u5B58\u30CE\u30FC\u30C8\u3092\u4E0A\u66F8\u304D").addOption("create-new", "\u65B0\u898F\u30CE\u30FC\u30C8\u3092\u4F5C\u6210").setValue(this.plugin.settings.duplicateIsbnAction).onChange(async (value) => {
        this.plugin.settings.duplicateIsbnAction = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/isbn-modal.ts
var import_obsidian6 = require("obsidian");

// src/book-api.ts
var import_obsidian2 = require("obsidian");
function normalizeIsbn(isbn) {
  return isbn.replace(/[\s\-]/g, "");
}
function isJapaneseIsbn(isbn) {
  return isbn.startsWith("978-4") || isbn.startsWith("9784") || isbn.startsWith("4");
}
async function fetchFromNDL(isbn) {
  var _a, _b;
  const url = `https://ndlsearch.ndl.go.jp/api/sru?operation=searchRetrieve&recordSchema=dcndl&recordPacking=xml&query=isbn%3D%22${isbn}%22`;
  try {
    const response = await (0, import_obsidian2.requestUrl)({ url });
    if (response.status !== 200)
      return null;
    const parser = new DOMParser();
    const xml = parser.parseFromString(response.text, "text/xml");
    const numberOfRecords = (_b = (_a = xml.querySelector("numberOfRecords")) == null ? void 0 : _a.textContent) == null ? void 0 : _b.trim();
    if (!numberOfRecords || numberOfRecords === "0")
      return null;
    const getTextContent = (tagName) => {
      var _a2;
      const elements = xml.getElementsByTagNameNS("*", tagName);
      for (let i = 0; i < elements.length; i++) {
        const text = (_a2 = elements[i].textContent) == null ? void 0 : _a2.trim();
        if (text)
          return text;
      }
      return "";
    };
    const title = getTextContent("title") || "";
    if (!title)
      return null;
    const author = getTextContent("creator") || getTextContent("contributor") || "";
    const publisher = getTextContent("publisher") || "";
    const publishDate = getTextContent("date") || "";
    const pages = parseInt(getTextContent("extent") || "0", 10) || 0;
    return {
      title,
      author,
      publisher,
      isbn,
      publishDate,
      pages,
      coverUrl: "",
      language: "ja"
    };
  } catch (e) {
    return null;
  }
}
async function fetchFromGoogleBooks(isbn, apiKey) {
  var _a, _b;
  let url = `https://www.googleapis.com/books/v1/volumes?q=isbn:${isbn}`;
  if (apiKey)
    url += `&key=${apiKey}`;
  try {
    const response = await (0, import_obsidian2.requestUrl)({ url });
    if (response.status !== 200)
      return null;
    const data = response.json;
    if (!data.items || data.items.length === 0)
      return null;
    const info = data.items[0].volumeInfo;
    if (!info)
      return null;
    const title = info.title || "";
    if (!title)
      return null;
    const author = (info.authors || []).join(", ");
    const publisher = info.publisher || "";
    const publishDate = info.publishedDate || "";
    const pages = info.pageCount || 0;
    const coverUrl = ((_a = info.imageLinks) == null ? void 0 : _a.thumbnail) || ((_b = info.imageLinks) == null ? void 0 : _b.smallThumbnail) || "";
    const language = info.language || "en";
    return {
      title,
      author,
      publisher,
      isbn,
      publishDate,
      pages,
      coverUrl: coverUrl.replace(/^http:/, "https:"),
      language
    };
  } catch (e) {
    return null;
  }
}
async function fetchFromOpenLibrary(isbn) {
  var _a, _b, _c, _d;
  const url = `https://openlibrary.org/api/books?bibkeys=ISBN:${isbn}&format=json&jscmd=data`;
  try {
    const response = await (0, import_obsidian2.requestUrl)({ url });
    if (response.status !== 200)
      return null;
    const data = response.json;
    const book = data[`ISBN:${isbn}`];
    if (!book)
      return null;
    const title = book.title || "";
    if (!title)
      return null;
    const author = (book.authors || []).map((a) => a.name).join(", ");
    const publisher = (book.publishers || []).map((p) => p.name).join(", ");
    const publishDate = book.publish_date || "";
    const pages = book.number_of_pages || 0;
    const coverUrl = ((_a = book.cover) == null ? void 0 : _a.large) || ((_b = book.cover) == null ? void 0 : _b.medium) || "";
    const language = ((_d = (_c = (book.languages || [{ key: "/languages/eng" }])[0]) == null ? void 0 : _c.key) == null ? void 0 : _d.split("/").pop()) === "jpn" ? "ja" : "en";
    return {
      title,
      author,
      publisher,
      isbn,
      publishDate,
      pages,
      coverUrl: coverUrl.replace(/^http:/, "https:"),
      language
    };
  } catch (e) {
    return null;
  }
}
function buildCoverUrl(isbn, metadata) {
  if (metadata.coverUrl)
    return metadata.coverUrl;
  return `https://covers.openlibrary.org/b/isbn/${isbn}-L.jpg`;
}
async function fetchByISBN(isbn, googleBooksApiKey) {
  var _a;
  const normalized = normalizeIsbn(isbn);
  let metadata = null;
  if (isJapaneseIsbn(normalized)) {
    metadata = await fetchFromNDL(normalized);
  }
  if (!metadata) {
    metadata = await fetchFromGoogleBooks(normalized, googleBooksApiKey);
  }
  if (!metadata) {
    metadata = await fetchFromOpenLibrary(normalized);
  }
  if (!metadata) {
    throw new Error(`\u66F8\u7C4D\u60C5\u5831\u304C\u898B\u3064\u304B\u308A\u307E\u305B\u3093\u3067\u3057\u305F: ISBN ${normalized}`);
  }
  if (!metadata.coverUrl) {
    const forCover = (_a = await fetchFromGoogleBooks(normalized, googleBooksApiKey)) != null ? _a : await fetchFromOpenLibrary(normalized);
    if (forCover == null ? void 0 : forCover.coverUrl) {
      metadata.coverUrl = forCover.coverUrl;
    }
  }
  metadata.coverUrl = buildCoverUrl(normalized, metadata);
  return metadata;
}

// src/note-creator.ts
var import_obsidian4 = require("obsidian");

// src/image-cache.ts
var import_obsidian3 = require("obsidian");
async function urlToWebpArrayBuffer(url) {
  var _a, _b;
  const response = await (0, import_obsidian3.requestUrl)({ url });
  if (response.status !== 200) {
    throw new Error(`\u753B\u50CF\u306E\u53D6\u5F97\u306B\u5931\u6557\u3057\u307E\u3057\u305F: ${response.status}`);
  }
  const contentType = ((_b = (_a = response.headers) == null ? void 0 : _a["content-type"]) == null ? void 0 : _b.split(";")[0].trim()) || "image/jpeg";
  const blob = new Blob([response.arrayBuffer], { type: contentType });
  const imageBitmap = await createImageBitmap(blob);
  if (imageBitmap.width <= 1 || imageBitmap.height <= 1) {
    throw new Error("\u30D7\u30EC\u30FC\u30B9\u30DB\u30EB\u30C0\u30FC\u753B\u50CF\u306E\u305F\u3081\u4FDD\u5B58\u3092\u30B9\u30AD\u30C3\u30D7\u3057\u307E\u3057\u305F");
  }
  const canvas = document.createElement("canvas");
  canvas.width = imageBitmap.width;
  canvas.height = imageBitmap.height;
  const ctx = canvas.getContext("2d");
  if (!ctx)
    throw new Error("Canvas context \u306E\u53D6\u5F97\u306B\u5931\u6557\u3057\u307E\u3057\u305F");
  ctx.drawImage(imageBitmap, 0, 0);
  return new Promise((resolve, reject) => {
    canvas.toBlob((webpBlob) => {
      if (!webpBlob) {
        reject(new Error("WebP \u5909\u63DB\u306B\u5931\u6557\u3057\u307E\u3057\u305F"));
        return;
      }
      webpBlob.arrayBuffer().then(resolve).catch(reject);
    }, "image/webp", 0.9);
  });
}
async function downloadCover(app, isbn, coverUrl, coversFolder) {
  const fileName = `${isbn}.webp`;
  const vaultPath = `${coversFolder}/${fileName}`;
  if (await app.vault.adapter.exists(vaultPath)) {
    return vaultPath;
  }
  if (!await app.vault.adapter.exists(coversFolder)) {
    await app.vault.createFolder(coversFolder);
  }
  const arrayBuffer = await urlToWebpArrayBuffer(coverUrl);
  await app.vault.adapter.writeBinary(vaultPath, arrayBuffer);
  return vaultPath;
}
async function saveCoverFromFileObject(app, fileNameKey, file, coversFolder) {
  const sanitized = fileNameKey.replace(/[\\/:*?"<>|]/g, "_").trim();
  const vaultPath = `${coversFolder}/${sanitized}.webp`;
  if (!await app.vault.adapter.exists(coversFolder)) {
    await app.vault.createFolder(coversFolder);
  }
  const imageBitmap = await createImageBitmap(file);
  const canvas = document.createElement("canvas");
  canvas.width = imageBitmap.width;
  canvas.height = imageBitmap.height;
  const ctx = canvas.getContext("2d");
  if (!ctx)
    throw new Error("Canvas context \u306E\u53D6\u5F97\u306B\u5931\u6557\u3057\u307E\u3057\u305F");
  ctx.drawImage(imageBitmap, 0, 0);
  const arrayBuffer = await new Promise((resolve, reject) => {
    canvas.toBlob((webpBlob) => {
      if (!webpBlob) {
        reject(new Error("WebP \u5909\u63DB\u306B\u5931\u6557\u3057\u307E\u3057\u305F"));
        return;
      }
      webpBlob.arrayBuffer().then(resolve).catch(reject);
    }, "image/webp", 0.9);
  });
  await app.vault.adapter.writeBinary(vaultPath, arrayBuffer);
  return vaultPath;
}
async function setManualCover(app, isbn, coversFolder) {
  var _a, _b, _c;
  const electron = (_a = window.require) == null ? void 0 : _a.call(window, "electron");
  if (!electron) {
    new import_obsidian3.Notice("Electron API \u304C\u5229\u7528\u3067\u304D\u307E\u305B\u3093\u3002\u30C7\u30B9\u30AF\u30C8\u30C3\u30D7\u7248 Obsidian \u3067\u5B9F\u884C\u3057\u3066\u304F\u3060\u3055\u3044\u3002");
    return null;
  }
  const { dialog } = electron.remote || electron;
  const result = await dialog.showOpenDialog({
    title: "\u8868\u7D19\u753B\u50CF\u3092\u9078\u629E",
    filters: [{ name: "WebP \u753B\u50CF", extensions: ["webp", "jpg", "jpeg", "png"] }],
    properties: ["openFile"]
  });
  if (result.canceled || !result.filePaths || result.filePaths.length === 0) {
    return null;
  }
  const sourcePath = result.filePaths[0];
  const vaultPath = `${coversFolder}/${isbn}.webp`;
  if (!await app.vault.adapter.exists(coversFolder)) {
    await app.vault.createFolder(coversFolder);
  }
  const fs = (_b = window.require) == null ? void 0 : _b.call(window, "fs");
  if (!fs) {
    new import_obsidian3.Notice("\u30D5\u30A1\u30A4\u30EB\u30B7\u30B9\u30C6\u30E0 API \u304C\u5229\u7528\u3067\u304D\u307E\u305B\u3093\u3002");
    return null;
  }
  const sourceBuffer = fs.readFileSync(sourcePath);
  const ext = (_c = sourcePath.split(".").pop()) == null ? void 0 : _c.toLowerCase();
  if (ext === "webp") {
    await app.vault.adapter.writeBinary(vaultPath, sourceBuffer.buffer);
  } else {
    const blob = new Blob([sourceBuffer], { type: "image/*" });
    const imageBitmap = await createImageBitmap(blob);
    const canvas = document.createElement("canvas");
    canvas.width = imageBitmap.width;
    canvas.height = imageBitmap.height;
    const ctx = canvas.getContext("2d");
    if (!ctx)
      throw new Error("Canvas context \u306E\u53D6\u5F97\u306B\u5931\u6557\u3057\u307E\u3057\u305F");
    ctx.drawImage(imageBitmap, 0, 0);
    const arrayBuffer = await new Promise((resolve, reject) => {
      canvas.toBlob((webpBlob) => {
        if (!webpBlob) {
          reject(new Error("WebP \u5909\u63DB\u306B\u5931\u6557\u3057\u307E\u3057\u305F"));
          return;
        }
        webpBlob.arrayBuffer().then(resolve).catch(reject);
      }, "image/webp", 0.9);
    });
    await app.vault.adapter.writeBinary(vaultPath, arrayBuffer);
  }
  return vaultPath;
}

// src/note-creator.ts
function sanitizeFileName(name) {
  return name.replace(/[\\/:*?"<>|]/g, "_").trim();
}
function buildFrontmatter(metadata, coverPath) {
  return {
    title: metadata.title,
    author: metadata.author,
    publisher: metadata.publisher,
    isbn: metadata.isbn,
    publishDate: metadata.publishDate,
    pages: metadata.pages,
    cover: coverPath,
    status: "to-read",
    progress: 0,
    startDate: "",
    endDate: "",
    rating: 0,
    language: metadata.language,
    tags: ["book"]
  };
}
function buildNoteBody() {
  return "\n## \u30E1\u30E2\u30FB\u611F\u60F3\n\n";
}
async function createBookNote(app, metadata, settings, prebuiltCoverPath) {
  const { booksFolder, coversFolder, duplicateIsbnAction } = settings;
  if (!await app.vault.adapter.exists(booksFolder)) {
    await app.vault.createFolder(booksFolder);
  }
  const existingFile = metadata.isbn ? findNoteByISBN(app, metadata.isbn) : null;
  if (existingFile) {
    if (duplicateIsbnAction === "open") {
      new import_obsidian4.Notice(`\u65E2\u5B58\u30CE\u30FC\u30C8\u3092\u958B\u304D\u307E\u3059: ${existingFile.name}`);
      await app.workspace.getLeaf(false).openFile(existingFile);
      return existingFile;
    } else if (duplicateIsbnAction === "overwrite") {
      return await overwriteNote(app, existingFile, metadata, coversFolder, settings, prebuiltCoverPath);
    }
  }
  const coverPath = prebuiltCoverPath !== void 0 ? prebuiltCoverPath : await downloadCoverSafe(app, metadata, coversFolder, settings);
  const baseName = sanitizeFileName(metadata.title);
  let fileName = `${baseName}.md`;
  let filePath = `${booksFolder}/${fileName}`;
  if (await app.vault.adapter.exists(filePath)) {
    fileName = `${baseName}-${metadata.isbn}.md`;
    filePath = `${booksFolder}/${fileName}`;
  }
  const frontmatter = buildFrontmatter(metadata, coverPath);
  const frontmatterStr = Object.entries(frontmatter).map(([k, v]) => {
    if (Array.isArray(v))
      return `${k}:
${v.map((i) => `  - ${i}`).join("\n")}`;
    if (typeof v === "string")
      return `${k}: "${v}"`;
    return `${k}: ${v}`;
  }).join("\n");
  const content = `---
${frontmatterStr}
---
${buildNoteBody()}`;
  const file = await app.vault.create(filePath, content);
  await app.workspace.getLeaf(false).openFile(file);
  new import_obsidian4.Notice(`\u66F8\u7C4D\u30CE\u30FC\u30C8\u3092\u4F5C\u6210\u3057\u307E\u3057\u305F: ${file.name}`);
  return file;
}
async function overwriteNote(app, file, metadata, coversFolder, settings, prebuiltCoverPath) {
  const coverPath = prebuiltCoverPath !== void 0 ? prebuiltCoverPath : await downloadCoverSafe(app, metadata, coversFolder, settings);
  const frontmatter = buildFrontmatter(metadata, coverPath);
  await app.fileManager.processFrontMatter(file, (fm) => {
    Object.assign(fm, frontmatter);
  });
  await app.workspace.getLeaf(false).openFile(file);
  new import_obsidian4.Notice(`\u66F8\u7C4D\u30CE\u30FC\u30C8\u3092\u66F4\u65B0\u3057\u307E\u3057\u305F: ${file.name}`);
  return file;
}
async function downloadCoverSafe(app, metadata, coversFolder, settings) {
  if (!metadata.coverUrl)
    return "";
  try {
    return await downloadCover(app, metadata.isbn, metadata.coverUrl, coversFolder);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    const isPlaceholder = message.includes("\u30D7\u30EC\u30FC\u30B9\u30DB\u30EB\u30C0\u30FC");
    if (isPlaceholder) {
      console.info("\u8868\u7D19\u753B\u50CF\u304C\u898B\u3064\u304B\u308A\u307E\u305B\u3093\u3067\u3057\u305F\uFF08\u30D7\u30EC\u30FC\u30B9\u30DB\u30EB\u30C0\u30FC\u306E\u305F\u3081\u30B9\u30AD\u30C3\u30D7\uFF09");
      new import_obsidian4.Notice(
        "\u8868\u7D19\u753B\u50CF\u304C\u898B\u3064\u304B\u308A\u307E\u305B\u3093\u3067\u3057\u305F\u3002\n\u624B\u52D5\u30D5\u30A9\u30FC\u30E0\u306E\u8868\u7D19\u30A8\u30EA\u30A2\u304B\u3089\u753B\u50CF\u3092\u8FFD\u52A0\u3067\u304D\u307E\u3059\u3002",
        6e3
      );
    } else {
      console.warn("\u8868\u7D19\u753B\u50CF\u306E\u53D6\u5F97\u306B\u5931\u6557\u3057\u307E\u3057\u305F:", err);
      const expectedPath = `${coversFolder}/${metadata.isbn || sanitizeFileName(metadata.title)}.webp`;
      new import_obsidian4.Notice(
        `\u8868\u7D19\u753B\u50CF\u306E\u53D6\u5F97\u306B\u5931\u6557\u3057\u307E\u3057\u305F\u3002
\u624B\u52D5\u3067 ${expectedPath} \u306B WebP \u753B\u50CF\u3092\u914D\u7F6E\u3057\u3066\u304F\u3060\u3055\u3044\u3002`,
        8e3
      );
    }
    return "";
  }
}
function findNoteByISBN(app, isbn) {
  var _a;
  const files = app.vault.getMarkdownFiles();
  for (const file of files) {
    const cache = app.metadataCache.getFileCache(file);
    if (((_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.isbn) === isbn) {
      return file;
    }
  }
  return null;
}
async function updateBookNote(app, metadata, settings) {
  var _a;
  const file = app.workspace.getActiveFile();
  if (!file) {
    new import_obsidian4.Notice("\u30A2\u30AF\u30C6\u30A3\u30D6\u306A\u30CE\u30FC\u30C8\u304C\u3042\u308A\u307E\u305B\u3093\u3002");
    return;
  }
  const cache = app.metadataCache.getFileCache(file);
  if (!((_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.isbn)) {
    new import_obsidian4.Notice("\u3053\u306E\u30CE\u30FC\u30C8\u306B\u306F ISBN \u30D5\u30A3\u30FC\u30EB\u30C9\u304C\u3042\u308A\u307E\u305B\u3093\u3002");
    return;
  }
  await overwriteNote(app, file, metadata, settings.coversFolder, settings);
}

// src/edit-modal.ts
var import_obsidian5 = require("obsidian");
var EditBookModal = class extends import_obsidian5.Modal {
  constructor(app, file, fm, settings) {
    super(app);
    this.pasteHandler = null;
    this.file = file;
    this.fm = fm;
    this.settings = settings;
  }
  onOpen() {
    var _a, _b;
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("bookshelf-modal");
    contentEl.createEl("h2", { text: "\u66F8\u7C4D\u30CE\u30FC\u30C8\u3092\u7DE8\u96C6" });
    let newCoverFile = null;
    const formEl = contentEl.createDiv("bookshelf-manual-form");
    const dropzoneEl = formEl.createDiv("bookshelf-dropzone");
    const dropzoneText = dropzoneEl.createDiv({
      cls: "bookshelf-dropzone-text",
      text: "\u8868\u7D19\u753B\u50CF\u3092\u30C9\u30ED\u30C3\u30D7 / \u30AF\u30EA\u30C3\u30AF / Ctrl+V \u3067\u8CBC\u308A\u4ED8\u3051"
    });
    let previewImg = null;
    const coverPath = String(this.fm.cover || "");
    const coverTFile = coverPath ? this.app.vault.getAbstractFileByPath(coverPath) : null;
    if (coverTFile instanceof import_obsidian5.TFile) {
      dropzoneText.style.display = "none";
      previewImg = dropzoneEl.createEl("img");
      previewImg.src = this.app.vault.getResourcePath(coverTFile);
    }
    const fileInput = document.createElement("input");
    fileInput.type = "file";
    fileInput.accept = ".jpg,.jpeg,.png,.webp";
    fileInput.style.display = "none";
    contentEl.appendChild(fileInput);
    const setPreviewFile = (file) => {
      newCoverFile = file;
      const objectUrl = URL.createObjectURL(file);
      if (previewImg) {
        previewImg.src = objectUrl;
      } else {
        dropzoneText.style.display = "none";
        previewImg = dropzoneEl.createEl("img");
        previewImg.src = objectUrl;
      }
    };
    this.pasteHandler = (e) => {
      var _a2;
      const items = (_a2 = e.clipboardData) == null ? void 0 : _a2.items;
      if (!items)
        return;
      for (const item of Array.from(items)) {
        if (item.type.startsWith("image/")) {
          const file = item.getAsFile();
          if (file) {
            setPreviewFile(file);
            e.preventDefault();
          }
          break;
        }
      }
    };
    document.addEventListener("paste", this.pasteHandler);
    dropzoneEl.addEventListener("click", () => fileInput.click());
    fileInput.addEventListener("change", () => {
      var _a2;
      const file = (_a2 = fileInput.files) == null ? void 0 : _a2[0];
      if (file)
        setPreviewFile(file);
    });
    dropzoneEl.addEventListener("dragover", (e) => {
      e.preventDefault();
      dropzoneEl.addClass("drag-over");
    });
    dropzoneEl.addEventListener("dragleave", () => {
      dropzoneEl.removeClass("drag-over");
    });
    dropzoneEl.addEventListener("drop", (e) => {
      var _a2, _b2;
      e.preventDefault();
      dropzoneEl.removeClass("drag-over");
      const file = (_b2 = (_a2 = e.dataTransfer) == null ? void 0 : _a2.files) == null ? void 0 : _b2[0];
      if (file && /\.(jpe?g|png|webp)$/i.test(file.name)) {
        setPreviewFile(file);
      }
    });
    const fieldsEl = formEl.createDiv("form-fields");
    let titleValue = String(this.fm.title || "");
    new import_obsidian5.Setting(fieldsEl).setName("\u30BF\u30A4\u30C8\u30EB").addText((text) => {
      text.setValue(titleValue);
      text.inputEl.style.width = "100%";
      text.onChange((v) => {
        titleValue = v;
      });
    });
    let authorValue = String(this.fm.author || "");
    new import_obsidian5.Setting(fieldsEl).setName("\u8457\u8005").addText((text) => {
      text.setValue(authorValue);
      text.inputEl.style.width = "100%";
      text.onChange((v) => {
        authorValue = v;
      });
    });
    let publisherValue = String(this.fm.publisher || "");
    new import_obsidian5.Setting(fieldsEl).setName("\u51FA\u7248\u793E").addText((text) => {
      text.setValue(publisherValue);
      text.inputEl.style.width = "100%";
      text.onChange((v) => {
        publisherValue = v;
      });
    });
    let publishDateValue = String(this.fm.publishDate || "");
    new import_obsidian5.Setting(fieldsEl).setName("\u51FA\u7248\u65E5").addText((text) => {
      text.setValue(publishDateValue);
      text.inputEl.style.width = "100%";
      text.onChange((v) => {
        publishDateValue = v;
      });
    });
    let pagesValue = String(this.fm.pages || "");
    new import_obsidian5.Setting(fieldsEl).setName("\u30DA\u30FC\u30B8\u6570").addText((text) => {
      text.setValue(pagesValue);
      text.inputEl.style.width = "100%";
      text.onChange((v) => {
        pagesValue = v;
      });
    });
    let languageValue = String(this.fm.language || "ja");
    new import_obsidian5.Setting(fieldsEl).setName("\u8A00\u8A9E").addDropdown((dd) => {
      dd.addOption("ja", "\u65E5\u672C\u8A9E");
      dd.addOption("en", "English");
      dd.addOption("other", "\u305D\u306E\u4ED6");
      dd.setValue(languageValue);
      dd.onChange((v) => {
        languageValue = v;
      });
    });
    let statusValue = String(this.fm.status || "to-read");
    new import_obsidian5.Setting(contentEl).setName("\u30B9\u30C6\u30FC\u30BF\u30B9").addDropdown((dd) => {
      dd.addOption("to-read", "\u8AAD\u307F\u305F\u3044");
      dd.addOption("reading", "\u8AAD\u66F8\u4E2D");
      dd.addOption("completed", "\u8AAD\u4E86");
      dd.addOption("abandoned", "\u4E2D\u65AD");
      dd.setValue(statusValue);
      dd.onChange((v) => {
        statusValue = v;
      });
    });
    let progressValue = Number((_a = this.fm.progress) != null ? _a : 0);
    const progressSetting = new import_obsidian5.Setting(contentEl).setName("\u9032\u6357").setDesc(`${progressValue}%`);
    progressSetting.addSlider((slider) => {
      slider.setLimits(0, 100, 1);
      slider.setValue(progressValue);
      slider.onChange((v) => {
        progressValue = v;
        progressSetting.setDesc(`${v}%`);
      });
    });
    let ratingValue = Number((_b = this.fm.rating) != null ? _b : 0);
    const ratingSetting = new import_obsidian5.Setting(contentEl).setName("\u8A55\u4FA1").setDesc(`${ratingValue}`);
    ratingSetting.addSlider((slider) => {
      slider.setLimits(0, 5, 1);
      slider.setValue(ratingValue);
      slider.onChange((v) => {
        ratingValue = v;
        ratingSetting.setDesc(`${v}`);
      });
    });
    let startDateValue = String(this.fm.startDate || "");
    let endDateValue = String(this.fm.endDate || "");
    new import_obsidian5.Setting(contentEl).setName("\u958B\u59CB\u65E5").addText((text) => {
      text.setPlaceholder("\u4F8B: 2024-01-01");
      text.setValue(startDateValue);
      text.onChange((v) => {
        startDateValue = v;
      });
    });
    new import_obsidian5.Setting(contentEl).setName("\u7D42\u4E86\u65E5").addText((text) => {
      text.setPlaceholder("\u4F8B: 2024-03-31");
      text.setValue(endDateValue);
      text.onChange((v) => {
        endDateValue = v;
      });
    });
    const isbnStr = String(this.fm.isbn || "");
    if (isbnStr) {
      new import_obsidian5.Setting(contentEl).setName("ISBN").setDesc(isbnStr);
    }
    new import_obsidian5.Setting(contentEl).addButton((btn) => {
      btn.setButtonText("\u4FDD\u5B58").setCta().onClick(async () => {
        try {
          let newCoverPath = null;
          if (newCoverFile) {
            const key = String(this.fm.isbn || this.fm.title || "book");
            newCoverPath = await saveCoverFromFileObject(
              this.app,
              key,
              newCoverFile,
              this.settings.coversFolder
            );
          }
          await this.app.fileManager.processFrontMatter(this.file, (front) => {
            front.title = titleValue;
            front.author = authorValue;
            front.publisher = publisherValue;
            front.publishDate = publishDateValue;
            front.pages = parseInt(pagesValue) || front.pages;
            front.language = languageValue;
            front.status = statusValue;
            front.progress = progressValue;
            front.rating = ratingValue;
            front.startDate = startDateValue;
            front.endDate = endDateValue;
            if (newCoverPath)
              front.cover = newCoverPath;
          });
          new import_obsidian5.Notice("\u66F8\u7C4D\u30CE\u30FC\u30C8\u3092\u66F4\u65B0\u3057\u307E\u3057\u305F");
          this.close();
        } catch (err) {
          const message = err instanceof Error ? err.message : String(err);
          new import_obsidian5.Notice(`\u30A8\u30E9\u30FC: ${message}`);
        }
      });
    }).addButton((btn) => {
      btn.setButtonText("\u30AD\u30E3\u30F3\u30BB\u30EB").onClick(() => this.close());
    });
  }
  onClose() {
    if (this.pasteHandler) {
      document.removeEventListener("paste", this.pasteHandler);
      this.pasteHandler = null;
    }
    this.contentEl.empty();
  }
};

// src/isbn-modal.ts
function normalizeIsbn2(input) {
  const raw = input.replace(/[\s\-]/g, "");
  if (raw.length === 10 && /^\d{9}[\dXx]$/.test(raw)) {
    return convertIsbn10To13(raw);
  }
  return raw;
}
function convertIsbn10To13(isbn10) {
  const digits = "978" + isbn10.slice(0, 9);
  let sum = 0;
  for (let i = 0; i < 12; i++) {
    sum += parseInt(digits[i]) * (i % 2 === 0 ? 1 : 3);
  }
  const check = (10 - sum % 10) % 10;
  return digits + check.toString();
}
function isValidIsbn(isbn) {
  return /^\d{13}$/.test(isbn) || /^\d{9}[\dXx]$/.test(isbn);
}
var ISBNModal = class extends import_obsidian6.Modal {
  constructor(app, settings) {
    super(app);
    this.inputEl = null;
    this.statusEl = null;
    this.isLoading = false;
    this.settings = settings;
  }
  onOpen() {
    this.showIsbnForm();
  }
  onClose() {
    this.contentEl.empty();
  }
  showIsbnForm() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("bookshelf-modal");
    contentEl.createEl("h2", { text: "ISBN \u304B\u3089\u672C\u3092\u8FFD\u52A0" });
    new import_obsidian6.Setting(contentEl).setName("ISBN").setDesc("ISBN-10 \u307E\u305F\u306F ISBN-13 \u3092\u5165\u529B\u3057\u3066\u304F\u3060\u3055\u3044").addText((text) => {
      text.setPlaceholder("\u4F8B: 9784000000000");
      text.inputEl.style.width = "220px";
      this.inputEl = text.inputEl;
      text.inputEl.addEventListener("keydown", (e) => {
        if (e.key === "Enter")
          this.handleSearch();
      });
    });
    new import_obsidian6.Setting(contentEl).addButton((btn) => {
      btn.setButtonText("\u691C\u7D22\u3057\u3066\u8FFD\u52A0").setCta().onClick(() => this.handleSearch());
    }).addButton((btn) => {
      btn.setButtonText("\u624B\u52D5\u3067\u5165\u529B").onClick(() => {
        var _a, _b;
        const raw = (_b = (_a = this.inputEl) == null ? void 0 : _a.value) != null ? _b : "";
        const isbn = raw ? normalizeIsbn2(raw) : "";
        this.showManualForm(isbn);
      });
    });
    this.statusEl = contentEl.createDiv();
    setTimeout(() => {
      var _a;
      return (_a = this.inputEl) == null ? void 0 : _a.focus();
    }, 50);
  }
  showManualForm(isbn) {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("bookshelf-modal");
    contentEl.createEl("h2", { text: "\u66F8\u7C4D\u60C5\u5831\u3092\u624B\u52D5\u3067\u5165\u529B" });
    let coverFile = null;
    const formEl = contentEl.createDiv("bookshelf-manual-form");
    const dropzoneEl = formEl.createDiv("bookshelf-dropzone");
    const dropzoneText = dropzoneEl.createDiv({
      cls: "bookshelf-dropzone-text",
      text: "\u8868\u7D19\u753B\u50CF\u3092\u30C9\u30ED\u30C3\u30D7 / \u30AF\u30EA\u30C3\u30AF / Ctrl+V \u3067\u8CBC\u308A\u4ED8\u3051"
    });
    let previewImg = null;
    const fileInput = document.createElement("input");
    fileInput.type = "file";
    fileInput.accept = ".jpg,.jpeg,.png,.webp";
    fileInput.style.display = "none";
    contentEl.appendChild(fileInput);
    const setPreviewFile = (file) => {
      coverFile = file;
      const objectUrl = URL.createObjectURL(file);
      if (previewImg) {
        previewImg.src = objectUrl;
      } else {
        dropzoneText.style.display = "none";
        previewImg = dropzoneEl.createEl("img");
        previewImg.src = objectUrl;
      }
    };
    const pasteHandler = (e) => {
      var _a;
      const items = (_a = e.clipboardData) == null ? void 0 : _a.items;
      if (!items)
        return;
      for (const item of Array.from(items)) {
        if (item.type.startsWith("image/")) {
          const file = item.getAsFile();
          if (file) {
            setPreviewFile(file);
            e.preventDefault();
          }
          break;
        }
      }
    };
    document.addEventListener("paste", pasteHandler);
    dropzoneEl.addEventListener("click", () => fileInput.click());
    fileInput.addEventListener("change", () => {
      var _a;
      const file = (_a = fileInput.files) == null ? void 0 : _a[0];
      if (file)
        setPreviewFile(file);
    });
    dropzoneEl.addEventListener("dragover", (e) => {
      e.preventDefault();
      dropzoneEl.addClass("drag-over");
    });
    dropzoneEl.addEventListener("dragleave", () => {
      dropzoneEl.removeClass("drag-over");
    });
    dropzoneEl.addEventListener("drop", (e) => {
      var _a, _b;
      e.preventDefault();
      dropzoneEl.removeClass("drag-over");
      const file = (_b = (_a = e.dataTransfer) == null ? void 0 : _a.files) == null ? void 0 : _b[0];
      if (file && /\.(jpe?g|png|webp)$/i.test(file.name)) {
        setPreviewFile(file);
      }
    });
    const fieldsEl = formEl.createDiv("form-fields");
    let titleValue = "";
    new import_obsidian6.Setting(fieldsEl).setName("\u30BF\u30A4\u30C8\u30EB *").addText((text) => {
      text.setPlaceholder("\u66F8\u7C4D\u30BF\u30A4\u30C8\u30EB");
      text.inputEl.style.width = "100%";
      text.onChange((v) => {
        titleValue = v;
      });
    });
    let authorValue = "";
    new import_obsidian6.Setting(fieldsEl).setName("\u8457\u8005").addText((text) => {
      text.setPlaceholder("\u8457\u8005\u540D");
      text.inputEl.style.width = "100%";
      text.onChange((v) => {
        authorValue = v;
      });
    });
    let publisherValue = "";
    new import_obsidian6.Setting(fieldsEl).setName("\u51FA\u7248\u793E").addText((text) => {
      text.setPlaceholder("\u51FA\u7248\u793E\u540D");
      text.inputEl.style.width = "100%";
      text.onChange((v) => {
        publisherValue = v;
      });
    });
    let publishDateValue = "";
    new import_obsidian6.Setting(fieldsEl).setName("\u51FA\u7248\u65E5").addText((text) => {
      text.setPlaceholder("\u4F8B: 2023-01-01");
      text.inputEl.style.width = "100%";
      text.onChange((v) => {
        publishDateValue = v;
      });
    });
    let pagesValue = "";
    new import_obsidian6.Setting(fieldsEl).setName("\u30DA\u30FC\u30B8\u6570").addText((text) => {
      text.setPlaceholder("\u4F8B: 300");
      text.inputEl.style.width = "100%";
      text.onChange((v) => {
        pagesValue = v;
      });
    });
    let languageValue = "ja";
    new import_obsidian6.Setting(fieldsEl).setName("\u8A00\u8A9E").addDropdown((dd) => {
      dd.addOption("ja", "\u65E5\u672C\u8A9E");
      dd.addOption("en", "English");
      dd.addOption("other", "\u305D\u306E\u4ED6");
      dd.setValue("ja");
      dd.onChange((v) => {
        languageValue = v;
      });
    });
    const statusEl = contentEl.createDiv();
    new import_obsidian6.Setting(contentEl).addButton((btn) => {
      btn.setButtonText("\u767B\u9332").setCta().onClick(async () => {
        const title = titleValue.trim();
        if (!title) {
          statusEl.empty();
          statusEl.createDiv({
            cls: "bookshelf-error",
            text: "\u30BF\u30A4\u30C8\u30EB\u306F\u5FC5\u9808\u3067\u3059"
          });
          return;
        }
        const normalizedIsbn = isbn && isValidIsbn(isbn) ? isbn : "";
        const metadata = {
          title,
          author: authorValue.trim(),
          publisher: publisherValue.trim(),
          isbn: normalizedIsbn,
          publishDate: publishDateValue.trim(),
          pages: parseInt(pagesValue) || 0,
          coverUrl: "",
          language: languageValue
        };
        let coverPath = "";
        if (coverFile) {
          try {
            coverPath = await saveCoverFromFileObject(
              this.app,
              normalizedIsbn || title,
              coverFile,
              this.settings.coversFolder
            );
          } catch (err) {
            console.warn("\u8868\u7D19\u753B\u50CF\u306E\u4FDD\u5B58\u306B\u5931\u6557\u3057\u307E\u3057\u305F:", err);
          }
        }
        try {
          await createBookNote(this.app, metadata, this.settings, coverPath || void 0);
          document.removeEventListener("paste", pasteHandler);
          this.close();
        } catch (err) {
          const message = err instanceof Error ? err.message : String(err);
          statusEl.empty();
          statusEl.createDiv({
            cls: "bookshelf-error",
            text: `\u30A8\u30E9\u30FC: ${message}`
          });
          new import_obsidian6.Notice(`\u30A8\u30E9\u30FC: ${message}`);
        }
      });
    }).addButton((btn) => {
      btn.setButtonText("\u623B\u308B").onClick(() => {
        document.removeEventListener("paste", pasteHandler);
        this.showIsbnForm();
      });
    });
  }
  async handleSearch() {
    var _a, _b, _c;
    if (this.isLoading)
      return;
    const raw = (_b = (_a = this.inputEl) == null ? void 0 : _a.value) != null ? _b : "";
    const isbn = normalizeIsbn2(raw);
    if (!isValidIsbn(isbn.replace(/[\s\-]/g, ""))) {
      this.showError("\u6709\u52B9\u306A ISBN \u3092\u5165\u529B\u3057\u3066\u304F\u3060\u3055\u3044\uFF0810\u6841\u307E\u305F\u306F13\u6841\u306E\u6570\u5B57\uFF09\u3002");
      return;
    }
    this.setLoading(true);
    try {
      const metadata = await fetchByISBN(isbn, this.settings.googleBooksApiKey || void 0);
      this.showPreview(metadata.title, metadata.author);
      const file = await createBookNote(this.app, metadata, this.settings);
      this.close();
      const cachedFm = (_c = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _c.frontmatter;
      const fm = cachedFm != null ? cachedFm : {
        title: metadata.title,
        author: metadata.author,
        publisher: metadata.publisher,
        isbn: metadata.isbn,
        publishDate: metadata.publishDate,
        pages: metadata.pages,
        cover: "",
        status: "to-read",
        progress: 0,
        startDate: "",
        endDate: "",
        rating: 0,
        language: metadata.language,
        tags: ["book"]
      };
      new EditBookModal(this.app, file, fm, this.settings).open();
    } catch (e) {
      this.showManualForm(isbn);
      new import_obsidian6.Notice("\u66F8\u7C4D\u60C5\u5831\u304C\u898B\u3064\u304B\u308A\u307E\u305B\u3093\u3067\u3057\u305F\u3002\u624B\u52D5\u3067\u5165\u529B\u3057\u3066\u304F\u3060\u3055\u3044\u3002");
    } finally {
      this.setLoading(false);
    }
  }
  setLoading(loading) {
    this.isLoading = loading;
    if (!this.statusEl)
      return;
    this.statusEl.empty();
    if (loading) {
      const spinnerEl = this.statusEl.createDiv("bookshelf-spinner");
      spinnerEl.createDiv("bookshelf-spinner-icon");
      spinnerEl.createSpan({ text: "\u66F8\u7C4D\u60C5\u5831\u3092\u53D6\u5F97\u4E2D..." });
    }
  }
  showError(message) {
    if (!this.statusEl)
      return;
    this.statusEl.empty();
    this.statusEl.createDiv({
      cls: "bookshelf-error",
      text: `\u30A8\u30E9\u30FC: ${message}`
    });
  }
  showPreview(title, author) {
    if (!this.statusEl)
      return;
    this.statusEl.empty();
    const preview = this.statusEl.createDiv("bookshelf-result-preview");
    preview.createEl("h3", { text: title });
    preview.createEl("p", { text: author });
  }
};

// src/book-select-modal.ts
var import_obsidian7 = require("obsidian");
var BookSelectModal = class extends import_obsidian7.FuzzySuggestModal {
  constructor(app, settings) {
    super(app);
    this.settings = settings;
    this.setPlaceholder("\u66F8\u7C4D\u30CE\u30FC\u30C8\u3092\u691C\u7D22...");
  }
  getItems() {
    return this.app.vault.getMarkdownFiles().filter((file) => {
      const cache = this.app.metadataCache.getFileCache(file);
      const fm = cache == null ? void 0 : cache.frontmatter;
      return fm && (fm.isbn !== void 0 || Array.isArray(fm.tags) && fm.tags.includes("book"));
    });
  }
  getItemText(file) {
    const cache = this.app.metadataCache.getFileCache(file);
    const fm = cache == null ? void 0 : cache.frontmatter;
    const title = (fm == null ? void 0 : fm.title) ? String(fm.title) : file.basename;
    const hasCover = !!(fm == null ? void 0 : fm.cover);
    return hasCover ? title : `${title} (\u8868\u7D19\u306A\u3057)`;
  }
  onChooseItem(file) {
    var _a;
    const cache = this.app.metadataCache.getFileCache(file);
    const fm = (_a = cache == null ? void 0 : cache.frontmatter) != null ? _a : {};
    new EditBookModal(this.app, file, fm, this.settings).open();
  }
};

// src/main.ts
var BookshelfPlugin = class extends import_obsidian8.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("book-open", "ISBN \u304B\u3089\u672C\u3092\u8FFD\u52A0", () => {
      new ISBNModal(this.app, this.settings).open();
    });
    this.addRibbonIcon("book-marked", "\u66F8\u7C4D\u30CE\u30FC\u30C8\u3092\u7DE8\u96C6", () => {
      new BookSelectModal(this.app, this.settings).open();
    });
    this.addCommand({
      id: "add-book-by-isbn",
      name: "ISBN \u304B\u3089\u672C\u3092\u8FFD\u52A0",
      callback: () => {
        new ISBNModal(this.app, this.settings).open();
      }
    });
    this.addCommand({
      id: "update-book-note",
      name: "\u66F8\u7C4D\u30CE\u30FC\u30C8\u3092\u66F4\u65B0",
      checkCallback: (checking) => {
        var _a;
        const file = this.app.workspace.getActiveFile();
        if (!file)
          return false;
        const cache = this.app.metadataCache.getFileCache(file);
        if (!((_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.isbn))
          return false;
        if (!checking) {
          this.handleUpdateNote(file, cache.frontmatter.isbn);
        }
        return true;
      }
    });
    this.addCommand({
      id: "set-manual-cover",
      name: "\u8868\u7D19\u753B\u50CF\u3092\u624B\u52D5\u3067\u8A2D\u5B9A",
      checkCallback: (checking) => {
        var _a;
        const file = this.app.workspace.getActiveFile();
        if (!file)
          return false;
        const cache = this.app.metadataCache.getFileCache(file);
        if (!((_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.isbn))
          return false;
        if (!checking) {
          this.handleSetManualCover(file, cache.frontmatter.isbn);
        }
        return true;
      }
    });
    this.addCommand({
      id: "edit-book-note",
      name: "\u66F8\u7C4D\u30CE\u30FC\u30C8\u3092\u7DE8\u96C6",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (!file)
          return false;
        const cache = this.app.metadataCache.getFileCache(file);
        const fm = cache == null ? void 0 : cache.frontmatter;
        const isBook = fm && (fm.isbn !== void 0 || Array.isArray(fm.tags) && fm.tags.includes("book"));
        if (!isBook)
          return false;
        if (!checking) {
          new EditBookModal(this.app, file, fm, this.settings).open();
        }
        return true;
      }
    });
    this.addCommand({
      id: "select-and-edit-book-note",
      name: "\u66F8\u7C4D\u30CE\u30FC\u30C8\u3092\u9078\u629E\u3057\u3066\u7DE8\u96C6",
      callback: () => {
        new BookSelectModal(this.app, this.settings).open();
      }
    });
    this.addSettingTab(new BookshelfSettingTab(this.app, this));
    await this.ensureBasesFile();
  }
  async handleUpdateNote(file, isbn) {
    try {
      new import_obsidian8.Notice("\u66F8\u7C4D\u60C5\u5831\u3092\u53D6\u5F97\u4E2D...");
      const metadata = await fetchByISBN(isbn, this.settings.googleBooksApiKey || void 0);
      await updateBookNote(this.app, metadata, this.settings);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      new import_obsidian8.Notice(`\u30A8\u30E9\u30FC: ${message}`);
    }
  }
  async handleSetManualCover(file, isbn) {
    try {
      const vaultPath = await setManualCover(this.app, isbn, this.settings.coversFolder);
      if (!vaultPath)
        return;
      await this.app.fileManager.processFrontMatter(file, (fm) => {
        fm.cover = vaultPath;
      });
      new import_obsidian8.Notice("\u8868\u7D19\u753B\u50CF\u3092\u8A2D\u5B9A\u3057\u307E\u3057\u305F\u3002");
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      new import_obsidian8.Notice(`\u30A8\u30E9\u30FC: ${message}`);
    }
  }
  async ensureBasesFile() {
    const basesPath = `${this.settings.booksFolder}/\u672C\u68DA.base`;
    if (await this.app.vault.adapter.exists(basesPath))
      return;
    if (!await this.app.vault.adapter.exists(this.settings.booksFolder)) {
      await this.app.vault.createFolder(this.settings.booksFolder);
    }
    const basesContent = JSON.stringify(
      {
        filters: {
          conditions: [{ field: "tags", operator: "contains", value: "book" }]
        },
        views: [
          {
            type: "cards",
            name: "\u672C\u68DA",
            coverField: "cover",
            fields: ["title", "author", "status", "progress", "rating"]
          },
          {
            type: "cards",
            name: "\u8AAD\u307F\u305F\u3044",
            coverField: "cover",
            fields: ["title", "author", "rating"],
            filters: {
              conditions: [
                { field: "tags", operator: "contains", value: "book" },
                { field: "status", operator: "equals", value: "to-read" }
              ]
            }
          },
          {
            type: "cards",
            name: "\u8AAD\u66F8\u4E2D",
            coverField: "cover",
            fields: ["title", "author", "progress"],
            filters: {
              conditions: [
                { field: "tags", operator: "contains", value: "book" },
                { field: "status", operator: "equals", value: "reading" }
              ]
            }
          },
          {
            type: "cards",
            name: "\u8AAD\u4E86",
            coverField: "cover",
            fields: ["title", "author", "rating", "endDate"],
            filters: {
              conditions: [
                { field: "tags", operator: "contains", value: "book" },
                { field: "status", operator: "equals", value: "completed" }
              ]
            }
          }
        ]
      },
      null,
      2
    );
    await this.app.vault.create(basesPath, basesContent);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  onunload() {
  }
};
